import DiPaolo.models.cliente
import DiPaolo.models.login
import DiPaolo.models.checkin
import DiPaolo.models.premio
import DiPaolo.models.retirada_premio
import DiPaolo.models.item_cardapio
import DiPaolo.models.pedido
import DiPaolo.models.pedido_item
import DiPaolo.models.campanha
import DiPaolo.models.configuracao
import DiPaolo.models.funcionario
import DiPaolo.models.cliente_avalia_funcionario
import DiPaolo.models.slide
import DiPaolo.models.mensagem
